<?php
        $apiKey="rzp_test_iMUODsJ1SFzhSk";
        include '../connection.php';
        session_start();
        $session=$_SESSION['id'];
		
		$sy="SELECT id FROM order_tbl where order_tbl.login_id='$session' and status='unpaid'";
        $t=mysqli_query($con,$sy);
        $row = mysqli_fetch_array($t);
		$r=$row['id'];
    


		
		
		$anc=$_GET['order'];
		$sr="SELECT SUM(totalprice) FROM tbl_cart where id='$anc'";
        $tt=mysqli_query($con,$sr);
        while ($rows = mysqli_fetch_array($tt)) {
       
       $amount=$rows['SUM(totalprice)'];
    // $name=$row['name'];

	
		
		
		
        
?>
<form method="POST" action="payment_action.php?amount=<?php echo $amount; ?>&&ar=<?php echo $anc; ?>&&rer=<?php echo $r; ?>">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $apiKey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo $amount * 100; ?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-order_id="<?php rand(100000, 999999);?>"// Replace with the order_id generated by you in the backend.
    data-buttontext="Pay"
    data-name="Cruise Liner"
    data-description="Enjoy Your Time"
    data-image=""
    data-prefill.name=""
    data-prefill.email=""
    data-theme.color="#F37254"
></script>
<input type="hidden" custom="Hidden Element" name="hidden">
</form>
		<?php }?>
<!--style>
.razorpay-payment-button { display:none; }
</style>


<script type="text/javascript">
  $(document).ready(function(){
    $('.razorpay-payment-button').click();

});
</script-->